name: blog_repository
description: a repository that manages the blogs

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.1.0
  equatable: ^2.0.0
  firebase_storage: ^10.0.2
  flutter:
    sdk: flutter
  hive: ^2.0.4
