name: weight_repository
description: a repository for user weight managment

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.1.0
  equatable: ^2.0.0
  firebase_auth: ^1.1.2
